[[redirects]]
  from = "/api/*"
  to = "https://botbackend.xyz:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pc/home"
  to = "/pc/home"
  status = 301

[[redirects]]
  from = "/pc/login"
  to = "/pc/login"
  status = 301
