[[redirects]]
  from = "/api/*"
  to = "https://botbackend.xyz:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pc/login/"
  to = "/pc/login"
  status = 301

[[redirects]]
  from = "/pc/signup/"
  to = "/pc/signup"
  status = 301

[[redirects]]
  from = "/pc/changepassword/"
  to = "/pc/changepassword"
  status = 301

[[redirects]]
  from = "/pc/chat/"
  to = "/pc/home/"
  status = 301

[[redirects]]
  from = "/pc/home/"
  to = "/pc/home"
  status = 301
