[[redirects]]
  from = "/api/*"
  to = "https://botbackend.xyz:8080/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pc/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/pc/chat"
  to = "/"
  status = 301

[[redirects]]
  from = "/pc/login"
  to = "/"
  status = 301

[[redirects]]
  from = "/pc/signup"
  to = "/"
  status = 301

[[redirects]]
  from = "/pc/changepassword"
  to = "/"
  status = 301
